# Generated by Django 3.2.13 on 2022-05-17 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=25)),
                ('center', models.CharField(blank=True, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='District_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=25)),
                ('slug', models.SlugField(max_length=252, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donors_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=22)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=8)),
                ('blood_group', models.CharField(blank=True, max_length=6)),
                ('address', models.TextField(blank=True, max_length=50)),
                ('mail_id', models.EmailField(blank=True, max_length=25)),
                ('phone_no', models.IntegerField(blank=True)),
                ('center', models.CharField(blank=True, max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
