# Generated by Django 3.2.13 on 2022-05-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_district_tb_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers_tb',
            name='center',
            field=models.CharField(blank=True, max_length=35, unique=True),
        ),
    ]
